pipeline {
    agent none

    stages {
        
        stage('clone') {
            agent { label 'master'}
            steps {
                cleanWs()
                git url: "https://github.com/DattaRahegaonkar/E-Commerce-Web-App.git", branch: "main"
                
                sh 'docker build -t ecommerce-frontend Frontend/.'
                sh 'docker build -t ecommerce-backend Backend/.'
            }
        }
        
        stage("Pushing the Image on Docker Hub Repository") {
            agent { label 'master'}
            steps {
                sh "docker tag ecommerce-backend dattarahegaonkar09/ecommerce-backend"
                // sh "docker push dattarahegaonkar09/ecommerce-backend"
                        
                sh "docker tag ecommerce-frontend dattarahegaonkar09/ecommerce-frontend"
                // sh "docker push dattarahegaonkar09/ecommerce-frontend"
            }
        }
        
        stage('database deploy') {
            agent { label 'db-agent' }
            steps {
                git url: "https://github.com/DattaRahegaonkar/E-Commerce-Web-App.git", branch: "main"
                
                sh '''
                
                export MONGO_INITDB_ROOT_USERNAME=root
                export MONGO_INITDB_ROOT_PASSWORD=root123
                export MONGO_INITDB_DATABASE=ecommerceDB
                
                docker rm -f mongodb || true
                docker compose up -d mongodb
                '''
            }
        }
        
        stage('bakcend deploy') {
            agent { label 'backend-agent' }
            steps {
                git url: "https://github.com/DattaRahegaonkar/E-Commerce-Web-App.git", branch: "main"
                
                sh '''
                export MONGO_URI=mongodb://ecommerceuser:ecommerce123@10.0.3.219:27017/ecommerceDB
                export JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc1ODczODQ2NSwiaWF0IjoxNzU4NzM4NDY1fQ.KR_3H9DI8bbqR2xrFTSOufFwsdJIJhjSici5mYDXqtc
                export PORT=8081
                export NODE_ENV=development
                export ALLOWED_ORIGINS=http://localhost:5173,http://localhost:80,http://localhost:8081,http://localhost,http://3.254.22.207:80,http://3.254.22.207/,http://ecommerce.rahegaonkar.site
                
                docker rm -f backend || true
                docker compose up -d backend
                '''
            }
        }
        
        stage('frontend deploy') {
            agent { label 'bastion-agent' }
            steps {
                cleanWs()
                
                git url: "https://github.com/DattaRahegaonkar/E-Commerce-Web-App.git", branch: "main"
                
                sh '''
                export VITE_API_URL=http://10.0.2.8:8081
                
                docker rm -f frontend nginx || true
                docker compose up -d frontend nginx
                '''
            }
        }
        
    }
}
