apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secret-provider
  namespace: ecommerce
spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "ecommerce/backend-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: MONGO_URI
            objectAlias: MONGO_URI
          - path: JWT_SECRET
            objectAlias: JWT_SECRET
          - path: NODE_ENV
            objectAlias: NODE_ENV
          - path: PORT
            objectAlias: PORT
          - path: JWT_EXPIRES_IN
            objectAlias: JWT_EXPIRES_IN
          - path: ALLOWED_ORIGINS
            objectAlias: ALLOWED_ORIGINS

  secretObjects:
    - secretName: backend-secret
      type: Opaque
      data:
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: NODE_ENV
          key: NODE_ENV
        - objectName: PORT
          key: PORT
        - objectName: JWT_EXPIRES_IN
          key: JWT_EXPIRES_IN
        - objectName: ALLOWED_ORIGINS
          key: ALLOWED_ORIGINS
