apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: frontend-secret-provider
  namespace: ecommerce
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  provider: aws
  
  parameters:
    objects: |
      - objectName: "ecommerce/frontend-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: BACKEND_URL
            objectAlias: BACKEND_URL

  secretObjects:
    - secretName: frontend-secret
      type: Opaque
      data:
        - objectName: BACKEND_URL
          key: BACKEND_URL
