
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo-deployment
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root123
            - name: MONGO_INITDB_DATABASE
              value: ecommerceDB
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
          resources:
            requests:
              memory: "140Mi"
              cpu: "5m"
            limits:
              memory: "250Mi"
              cpu: "50m"
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      restartPolicy: Always